// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/phones": {
    params: {};
  };
  "/phones/:phoneId": {
    params: {
      "phoneId": string;
    };
  };
  "/plans": {
    params: {};
  };
  "/plans/:planId": {
    params: {
      "planId": string;
    };
  };
  "/compare": {
    params: {};
  };
  "/wishlist": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/phones" | "/phones/:phoneId" | "/plans" | "/plans/:planId" | "/compare" | "/wishlist";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/phones.tsx": {
    id: "routes/phones";
    page: "/phones" | "/phones/:phoneId";
  };
  "routes/phones._index.tsx": {
    id: "routes/phones._index";
    page: "/phones";
  };
  "routes/phones.$phoneId.tsx": {
    id: "routes/phones.$phoneId";
    page: "/phones/:phoneId";
  };
  "routes/plans.tsx": {
    id: "routes/plans";
    page: "/plans" | "/plans/:planId";
  };
  "routes/plans._index.tsx": {
    id: "routes/plans._index";
    page: "/plans";
  };
  "routes/plans.$planId.tsx": {
    id: "routes/plans.$planId";
    page: "/plans/:planId";
  };
  "routes/compare.tsx": {
    id: "routes/compare";
    page: "/compare";
  };
  "routes/wishlist.tsx": {
    id: "routes/wishlist";
    page: "/wishlist";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/phones": typeof import("./app/routes/phones.tsx");
  "routes/phones._index": typeof import("./app/routes/phones._index.tsx");
  "routes/phones.$phoneId": typeof import("./app/routes/phones.$phoneId.tsx");
  "routes/plans": typeof import("./app/routes/plans.tsx");
  "routes/plans._index": typeof import("./app/routes/plans._index.tsx");
  "routes/plans.$planId": typeof import("./app/routes/plans.$planId.tsx");
  "routes/compare": typeof import("./app/routes/compare.tsx");
  "routes/wishlist": typeof import("./app/routes/wishlist.tsx");
};