<?php

namespace Database\Seeders;

use App\Models\Phone;
use App\Models\PhoneBrand;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Seeds the phones table with realistic smartphones from major brands.
 *
 * These are real phone models with approximate specs and Dutch market prices.
 * The data doesn't need to be 100% accurate — it just needs to look convincing
 * in the demo and give the search/filter features meaningful data to work with.
 */
class PhoneSeeder extends Seeder
{
    public function run(): void
    {
        // Fetch brands by slug so we can reference them by name
        $brands = PhoneBrand::all()->keyBy('slug');

        $phones = [
            // --- SAMSUNG ---
            [
                'brand' => 'samsung',
                'name' => 'Samsung Galaxy S24 Ultra',
                'price_eur' => 1449.00,
                'release_year' => 2024,
                'screen_size' => 6.8,
                'storage_gb' => 256,
                'ram_gb' => 12,
                'battery_mah' => 5000,
                'camera_mp' => '200+12+50+10',
                'os' => 'Android 14',
                'color' => 'Titanium Black',
                'is_5g' => true,
            ],
            [
                'brand' => 'samsung',
                'name' => 'Samsung Galaxy S24',
                'price_eur' => 899.00,
                'release_year' => 2024,
                'screen_size' => 6.2,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 4000,
                'camera_mp' => '50+12+10',
                'os' => 'Android 14',
                'color' => 'Onyx Black',
                'is_5g' => true,
            ],
            [
                'brand' => 'samsung',
                'name' => 'Samsung Galaxy S24 FE',
                'price_eur' => 649.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 4700,
                'camera_mp' => '50+12+8',
                'os' => 'Android 14',
                'color' => 'Blue',
                'is_5g' => true,
            ],
            [
                'brand' => 'samsung',
                'name' => 'Samsung Galaxy A55',
                'price_eur' => 449.00,
                'release_year' => 2024,
                'screen_size' => 6.6,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 5000,
                'camera_mp' => '50+12+5',
                'os' => 'Android 14',
                'color' => 'Awesome Navy',
                'is_5g' => true,
            ],
            [
                'brand' => 'samsung',
                'name' => 'Samsung Galaxy A35',
                'price_eur' => 349.00,
                'release_year' => 2024,
                'screen_size' => 6.6,
                'storage_gb' => 128,
                'ram_gb' => 6,
                'battery_mah' => 5000,
                'camera_mp' => '50+8+5',
                'os' => 'Android 14',
                'color' => 'Awesome Lilac',
                'is_5g' => true,
            ],
            [
                'brand' => 'samsung',
                'name' => 'Samsung Galaxy A16',
                'price_eur' => 199.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 128,
                'ram_gb' => 4,
                'battery_mah' => 5000,
                'camera_mp' => '50+5+2',
                'os' => 'Android 14',
                'color' => 'Blue Black',
                'is_5g' => true,
            ],

            // --- APPLE ---
            [
                'brand' => 'apple',
                'name' => 'iPhone 16 Pro Max',
                'price_eur' => 1479.00,
                'release_year' => 2024,
                'screen_size' => 6.9,
                'storage_gb' => 256,
                'ram_gb' => 8,
                'battery_mah' => 4685,
                'camera_mp' => '48+12+48',
                'os' => 'iOS 18',
                'color' => 'Desert Titanium',
                'is_5g' => true,
            ],
            [
                'brand' => 'apple',
                'name' => 'iPhone 16 Pro',
                'price_eur' => 1229.00,
                'release_year' => 2024,
                'screen_size' => 6.3,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 3582,
                'camera_mp' => '48+12+48',
                'os' => 'iOS 18',
                'color' => 'Natural Titanium',
                'is_5g' => true,
            ],
            [
                'brand' => 'apple',
                'name' => 'iPhone 16',
                'price_eur' => 969.00,
                'release_year' => 2024,
                'screen_size' => 6.1,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 3561,
                'camera_mp' => '48+12',
                'os' => 'iOS 18',
                'color' => 'Black',
                'is_5g' => true,
            ],
            [
                'brand' => 'apple',
                'name' => 'iPhone 15',
                'price_eur' => 829.00,
                'release_year' => 2023,
                'screen_size' => 6.1,
                'storage_gb' => 128,
                'ram_gb' => 6,
                'battery_mah' => 3349,
                'camera_mp' => '48+12',
                'os' => 'iOS 17',
                'color' => 'Blue',
                'is_5g' => true,
            ],
            [
                'brand' => 'apple',
                'name' => 'iPhone SE (2024)',
                'price_eur' => 529.00,
                'release_year' => 2024,
                'screen_size' => 4.7,
                'storage_gb' => 64,
                'ram_gb' => 4,
                'battery_mah' => 2018,
                'camera_mp' => '12',
                'os' => 'iOS 18',
                'color' => 'Midnight',
                'is_5g' => true,
            ],

            // --- ONEPLUS ---
            [
                'brand' => 'oneplus',
                'name' => 'OnePlus 12',
                'price_eur' => 899.00,
                'release_year' => 2024,
                'screen_size' => 6.8,
                'storage_gb' => 256,
                'ram_gb' => 12,
                'battery_mah' => 5400,
                'camera_mp' => '50+48+64',
                'os' => 'Android 14',
                'color' => 'Silky Black',
                'is_5g' => true,
            ],
            [
                'brand' => 'oneplus',
                'name' => 'OnePlus Nord 4',
                'price_eur' => 499.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 256,
                'ram_gb' => 12,
                'battery_mah' => 5500,
                'camera_mp' => '50+8',
                'os' => 'Android 14',
                'color' => 'Obsidian Midnight',
                'is_5g' => true,
            ],
            [
                'brand' => 'oneplus',
                'name' => 'OnePlus Nord CE 4 Lite',
                'price_eur' => 299.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 5110,
                'camera_mp' => '50+2',
                'os' => 'Android 14',
                'color' => 'Super Silver',
                'is_5g' => true,
            ],

            // --- XIAOMI ---
            [
                'brand' => 'xiaomi',
                'name' => 'Xiaomi 14 Ultra',
                'price_eur' => 1299.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 512,
                'ram_gb' => 16,
                'battery_mah' => 5300,
                'camera_mp' => '50+50+50+50',
                'os' => 'Android 14',
                'color' => 'Black',
                'is_5g' => true,
            ],
            [
                'brand' => 'xiaomi',
                'name' => 'Xiaomi 14',
                'price_eur' => 799.00,
                'release_year' => 2024,
                'screen_size' => 6.4,
                'storage_gb' => 256,
                'ram_gb' => 12,
                'battery_mah' => 4610,
                'camera_mp' => '50+50+50',
                'os' => 'Android 14',
                'color' => 'Jade Green',
                'is_5g' => true,
            ],
            [
                'brand' => 'xiaomi',
                'name' => 'Xiaomi Redmi Note 13 Pro',
                'price_eur' => 349.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 256,
                'ram_gb' => 8,
                'battery_mah' => 5100,
                'camera_mp' => '200+8+2',
                'os' => 'Android 13',
                'color' => 'Midnight Black',
                'is_5g' => true,
            ],
            [
                'brand' => 'xiaomi',
                'name' => 'Xiaomi Redmi Note 13',
                'price_eur' => 199.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 128,
                'ram_gb' => 6,
                'battery_mah' => 5000,
                'camera_mp' => '108+8+2',
                'os' => 'Android 13',
                'color' => 'Mint Green',
                'is_5g' => false,
            ],

            // --- GOOGLE ---
            [
                'brand' => 'google',
                'name' => 'Google Pixel 9 Pro',
                'price_eur' => 1099.00,
                'release_year' => 2024,
                'screen_size' => 6.3,
                'storage_gb' => 128,
                'ram_gb' => 16,
                'battery_mah' => 4700,
                'camera_mp' => '50+48+48',
                'os' => 'Android 14',
                'color' => 'Obsidian',
                'is_5g' => true,
            ],
            [
                'brand' => 'google',
                'name' => 'Google Pixel 9',
                'price_eur' => 899.00,
                'release_year' => 2024,
                'screen_size' => 6.3,
                'storage_gb' => 128,
                'ram_gb' => 12,
                'battery_mah' => 4700,
                'camera_mp' => '50+48',
                'os' => 'Android 14',
                'color' => 'Wintergreen',
                'is_5g' => true,
            ],
            [
                'brand' => 'google',
                'name' => 'Google Pixel 8a',
                'price_eur' => 499.00,
                'release_year' => 2024,
                'screen_size' => 6.1,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 4492,
                'camera_mp' => '64+13',
                'os' => 'Android 14',
                'color' => 'Bay',
                'is_5g' => true,
            ],

            // --- MOTOROLA ---
            [
                'brand' => 'motorola',
                'name' => 'Motorola Edge 50 Pro',
                'price_eur' => 599.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 256,
                'ram_gb' => 12,
                'battery_mah' => 4500,
                'camera_mp' => '50+13+10',
                'os' => 'Android 14',
                'color' => 'Black Beauty',
                'is_5g' => true,
            ],
            [
                'brand' => 'motorola',
                'name' => 'Motorola Moto G84',
                'price_eur' => 279.00,
                'release_year' => 2024,
                'screen_size' => 6.6,
                'storage_gb' => 256,
                'ram_gb' => 12,
                'battery_mah' => 5000,
                'camera_mp' => '50+8',
                'os' => 'Android 13',
                'color' => 'Midnight Blue',
                'is_5g' => true,
            ],

            // --- NOTHING ---
            [
                'brand' => 'nothing',
                'name' => 'Nothing Phone (2a)',
                'price_eur' => 349.00,
                'release_year' => 2024,
                'screen_size' => 6.7,
                'storage_gb' => 128,
                'ram_gb' => 8,
                'battery_mah' => 5000,
                'camera_mp' => '50+50',
                'os' => 'Android 14',
                'color' => 'Black',
                'is_5g' => true,
            ],
            [
                'brand' => 'nothing',
                'name' => 'Nothing Phone (2)',
                'price_eur' => 599.00,
                'release_year' => 2023,
                'screen_size' => 6.7,
                'storage_gb' => 256,
                'ram_gb' => 12,
                'battery_mah' => 4700,
                'camera_mp' => '50+50',
                'os' => 'Android 14',
                'color' => 'Dark Grey',
                'is_5g' => true,
            ],
        ];

        foreach ($phones as $phoneData) {
            $brandSlug = $phoneData['brand'];
            unset($phoneData['brand']);

            Phone::create(array_merge($phoneData, [
                'phone_brand_id' => $brands[$brandSlug]->id,
                'slug' => Str::slug($phoneData['name']),
            ]));
        }
    }
}
